import { token } from './token';

export const semantic = {
	background: {
		base: token.black,
		elevated: token.gray.gray090,
	},
	button: {
		base: token.light.primary.normal,
		outlined: token.light.primary.normal,
		text: token.light.primary.normal,
		hover: token.light.primary.normal,
		active: token.light.primary.normal,
		disabled: token.gray.gray060,
		selected: token.light.primary.normal,
	},
	text: {
		title: token.gray.gray005,
		base: token.gray.gray010,
		summary: token.gray.gray020,
		subtitle: token.black,
		subBase: token.gray.gray080,
		subSummary: token.gray.gray060,
		placeholder: token.gray.gray040,
		disabled: token.gray.gray030,
		link: token.light.primary.normal,
		linkHover: token.light.primary.normal,
		linkActive: token.light.primary.normal,
		linkDisabled: token.gray.gray060,
		linkSelected: token.light.primary.normal,
		linkSub: token.gray.gray005,
		linkSubHover: token.gray.gray010,
		linkSubActive: token.gray.gray020,
		linkSubDisabled: token.gray.gray060,
		linkSubSelected: token.gray.gray005,
	},
	border: {
		base: token.gray.gray060,
		hover: token.gray.gray050,
		active: token.gray.gray040,
		disabled: token.gray.gray060,
		selected: token.gray.gray060,
	},
	icon: {
		base: token.gray.gray005,
		hover: token.gray.gray010,
		active: token.gray.gray020,
		disabled: token.gray.gray060,
		selected: token.gray.gray005,
	},
	shadow: {
		base: token.black,
	},
	line: {
		base: token.gray.gray060,
		hover: token.gray.gray050,
		active: token.gray.gray040,
		disabled: token.gray.gray060,
		selected: token.gray.gray060,
	},
} as const;
