import { token } from './token';

export const semantic = {
	background: {
		base: token.black,
		elevated: token.gray.gray090,
	},
	button: {
		base: token.primary.light.primary.normal,
		outlined: token.primary.light.main.buzzle040,
		text: token.primary.light.main.buzzle040,
		hover: token.primary.light.main.buzzle060,
		active: token.primary.light.main.buzzle070,
		disabled: token.gray.gray060,
		selected: token.primary.light.main.buzzle070,
	},
	text: {
		title: token.gray.gray005,
		base: token.gray.gray010,
		summary: token.gray.gray020,
		subtitle: token.black,
		subBase: token.gray.gray080,
		subSummary: token.gray.gray060,
		placeholder: token.gray.gray040,
		disabled: token.gray.gray030,
		link: token.tint.main.buzzle050,
		linkHover: token.tint.main.buzzle060,
		linkActive: token.tint.main.buzzle070,
		linkDisabled: token.gray.gray060,
		linkSelected: token.tint.main.buzzle060,
		linkSub: token.gray.gray005,
		linkSubHover: token.gray.gray010,
		linkSubActive: token.gray.gray020,
		linkSubDisabled: token.gray.gray060,
		linkSubSelected: token.gray.gray005,
	},
	border: {
		base: token.gray.gray060,
		hover: token.gray.gray050,
		active: token.gray.gray040,
		disabled: token.gray.gray060,
		selected: token.gray.gray060,
	},
	icon: {
		base: token.gray.gray005,
		hover: token.gray.gray010,
		active: token.gray.gray020,
		disabled: token.gray.gray060,
		selected: token.gray.gray005,
	},
	shadow: {
		base: token.black,
	},
	line: {
		base: token.gray.gray060,
		hover: token.gray.gray050,
		active: token.gray.gray040,
		disabled: token.gray.gray060,
		selected: token.gray.gray060,
	},
} as const;
